eduardo.valores.nombre= Ed
#Generando una ruta
eduardo.valores.ruta_images= 
eduardo.valores.url_images= http://localhost/home/edi/ImagesSpring/
#Añadiendo caracteristicas para email
eduardo.valores.stmp_server=
eduardo.valores.stmp_puerto=
eduardo.valores.stmp_user=
eduardo.valores.stmp_password=

eduardo.valores.smtp_auth.mail.smtp.auth=true
eduardo.valores.smtp_auth.mail.smtp.starttls.enable=true

